# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=5500)),
                ('article_img', models.FileField(blank=True, null=True, upload_to='uploaded')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('article_category', models.CharField(max_length=500)),
                ('article_writer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=500)),
                ('news_img', models.FileField(blank=True, null=True, upload_to='uploaded')),
                ('text', models.CharField(max_length=5500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.CharField(max_length=500)),
                ('news_writer', models.CharField(max_length=500)),
            ],
        ),
    ]
