# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=500)),
                ('img', models.FileField(blank=True, null=True, upload_to='uploaded')),
                ('text', models.TextField(max_length=5500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=500)),
                ('is_article', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='StockNews',
        ),
    ]
