# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171102_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='des', max_length=100),
            preserve_default=False,
        ),
    ]
