# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171107_1203'),
        ('posts', '0005_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='user',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
