# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 04:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171107_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(max_length=5500),
        ),
    ]
