# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171113_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
