# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20171113_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
