# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20171114_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), default='us', size=3),
            preserve_default=False,
        ),
    ]
