# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20171115_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_published']},
        ),
    ]
