# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20171115_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_tag',
            new_name='Main_Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='Tags',
        ),
    ]
