# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20171118_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('stock', models.CharField(max_length=60)),
                ('event', models.CharField(max_length=60)),
                ('importance', models.CharField(max_length=60)),
                ('actual', models.CharField(max_length=60)),
                ('predict', models.CharField(max_length=60)),
                ('previous', models.CharField(max_length=60)),
            ],
        ),
    ]
