# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guest_first_name', models.CharField(max_length=10, null=True)),
                ('Guest_last_name', models.CharField(max_length=10, null=True)),
                ('Guest_email', models.EmailField(max_length=50, null=True)),
                ('issue_options', models.CharField(choices=[('co', 'همکاری'), ('pb', 'مشکل در خرید'), ('ag', 'درخواست بازی'), ('o', 'موارد دیگر')], default='co', max_length=2)),
                ('message', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=250, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('expire_time', models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('city', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اصفهان', 'اصفهان'), ('اردبیل', 'اردبیل'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال_و_بختیاری'), ('خراسان جنوبی', 'خراسان_جنوبی'), ('خراسان رضوی', 'خراسان_رضوی'), ('خراسان شمالی', 'خراسان_شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سیستان و بلوچستان', 'سیستان_و_بلوچستان'), ('سمنان', 'سمنان'), ('فارس', 'فارس'), ('قم', 'قم'), ('قزوین', 'قزوین'), ('کهکیلویه و بویراحمد', 'کهکیلویه_و_بویراحمد'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('گیلان', 'گیلان'), ('گلستان', 'گلستان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], default='tehran', max_length=25)),
                ('pro_img', models.FileField(blank=True, null=True, upload_to='uploaded')),
                ('vip', models.BooleanField(default=False)),
                ('inbox', models.ManyToManyField(to='users.Inbox')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_options', models.CharField(choices=[('co', 'همکاری'), ('pb', 'مشکل در خرید'), ('ag', 'درخواست بازی'), ('o', 'موارد دیگر')], default='co', max_length=2)),
                ('message', models.TextField(max_length=250, null=True)),
                ('sender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
