# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_inbox'),
        ('users', '0003_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inbox',
            field=models.ManyToManyField(to='posts.Inbox'),
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
