# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171107_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='tehran', max_length=11),
            preserve_default=False,
        ),
    ]
